<x-app-layout>
   

    <div class="p-6">
        <div class="bg-white rounded-lg w-full p-10">
            <div class="flex items-center gap-3 mb-2">
                <div class="bg-blue-100/60 p-2 rounded-lg">
                    <x-heroicon-s-document-plus class="w-5 h-5 text-brand-blue" />
                </div>
                <div>
                    <h1 class="text-xl font-semibold text-brand-blue">Create Document</h1>
                    <p class="text-xs text-gray-400 font-medium">Please fill in all of the required details.</p>
                </div>
            </div>

            <div class="grid grid-cols lg:grid-cols-2 mt-6 gap-10">
                @include('components.create-document.document-information')
                                
                @include('components.create-document.document-actions')
            </div>

            <div class="flex flex-col items-start justify-start lg:items-end lg:justify-end gap-3 mt-10">
                <p class="italic text-gray-500 text-xs">Please note that the reference number is automatically generated by the system.</p>

                <div class="flex flex-col md:flex-row gap-3 w-full justify-end">
                    <button class="text-xs md:text-sm bg-gray-200 text-gray-700 font-semibold rounded-lg px-4 py-2" id="cancel-create">Cancel</button>
                    <button class="text-xs md:text-sm bg-brand-blue/20 rounded-lg px-4 py-2 text-brand-blue font-semibold" id="create-document">Create Document</button>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>