@props(['open' => 'loading' , 'message' => '', 'id' => ''])

<div x-show="{{ $open }}" id="{{ $id }}" x-cloak class="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
    <div class="bg-white rounded-lg p-6 flex flex-col items-center w-72 max-w-sm">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="100" height="100" style="shape-rendering: auto; display: block; background: rgb(255, 255, 255);" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle r="13" fill="#242424" cy="50" cx="37">
            <animate begin="-0.4347826086956521s" values="37;63;37" keyTimes="0;0.5;1" dur="0.8695652173913042s" repeatCount="indefinite" attributeName="cx"></animate>
            </circle>
            <circle r="13" fill="#00aeef" cy="50" cx="63">
            <animate begin="0s" values="37;63;37" keyTimes="0;0.5;1" dur="0.8695652173913042s" repeatCount="indefinite" attributeName="cx"></animate>
            </circle>
            <circle r="13" fill="#242424" cy="50" cx="37">
            <animate begin="-0.4347826086956521s" values="37;63;37" keyTimes="0;0.5;1" dur="0.8695652173913042s" repeatCount="indefinite" attributeName="cx"></animate>
            <animate repeatCount="indefinite" dur="0.8695652173913042s" keyTimes="0;0.499;0.5;1" calcMode="discrete" values="0;0;1;1" attributeName="fill-opacity"></animate>
            </circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg>
        <p class="text-md font-semibold text-gray-800">{{ $message }}</p>
    </div>
</div>